#!/usr/bin/env bash
# This scriptloops through 1 to 10  displays, displays "bad luck" on 4th iteration, "good luck" on 8th iteration and "Best School" on other iterations.

count=1
while [ $count -le 10 ]
do
  if [ $count == 4 ]
  then
    echo "bad luck"
  elif [ $count == 8 ]
  then
    echo "good luck"
  else
    echo "Best School"
  fi
  count=$((count + 1))
done
