#!/usr/bin/env bash
# This script displays the time for 12 hours and 59 minutes

hour=0
minute=1

while [ $hour -le 12 ]
do
   printf "%02d:%02d\n" $hour $minute
      echo "Hour: $hour"
   

   if [ $minute -eq 59 ]
   then
      minute=0
      ((hour++))
   else
      ((minute++))
   fi
done
